name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: CheckOut
      run: |
        git config user.name fiveseven-lambda
        git config user.email fiveseven.lambda@gmail.com
        git checkout release
        git merge master
    - name: Build
      run: cargo build --release
      working-directory: converter
    - name: Compile
      run: converter/target/release/converter
    - name: Commit
      run: |
        if [ "$(git diff)" != "" ]; then
          git add index.html
          git commit -m "compiled source -> index.html, $(date)"
          git push origin release
        fi
