name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: CheckOut
      run: |
        git pull origin release
        git merge master
    - name: Build
      run: cargo build --release
      working-directory: converter
    - name: Compile
      run: converter/target/release/converter
    - name: Commit
      run: |
        git config user.name fiveseven-lambda
        git config user.email fiveseven.lambda@gmail.com
        git add index.html
        git commit -m "action $(date)"
        git push origin release
